default:
  navigation:
    - title: 婴儿奶粉
      subtitle: Categories
      url: /t/formula
      items:
        - :title: 一段
          :url: /t/categories/formula/stage1
        - :title: 二段
          :url: /t/categories/formula/stage2
        - :title: 三段
          :url: /t/categories/formula/stage3
        - :title: 四段
          :url: /t/categories/formula/stage4
      #   - :title: Skirts
      #     :url: /t/women/skirts
      #   - :title: Dresses
      #     :url: /t/women/dresses
      #   - :title: Shirts and Blouses
      #     :url: /t/women/shirts-and-blouses
      #   - :title: Sweaters
      #     :url: /t/women/sweaters
      #   - :title: Tops and T-shirts
      #     :url: /t/women/tops-and-t-shirts
      #   - :title: Jackets and Coats
      #     :url: /t/women/jackets-and-coats
      # promo_banners:
      #   - subtitle: New collection
      #     title: Summer 2019
      #     url: /t/new-collection/summer-2019
      #     image: 'meganav/promo_banner_left-first-category.jpg'
      #   - subtitle: Special Offers
      #     title: Get up to 30% off
      #     url: /t/special-offers/30-off
      #     image: 'meganav/promo_banner_right-first-category.jpg'
    - title: 婴儿辅食
      subtitle: Categories
      url: /t/baby_food
      # items:
      #   - :title: Shirts
      #     :url: /t/men/shirts
      #   - :title: T-shirts
      #     :url: /t/men/t-shirts
      #   - :title: Sweaters
      #     :url: /t/men/sweaters
      #   - :title: Jackets and Coats
      #     :url: /t/men/jackets-and-coats
      # promo_banners:
      #   - subtitle: New collection
      #     title: Summer 2019
      #     url: /t/new-collection/summer-2019
      #     image: 'meganav/promo_banner_left-second-category.jpg'
      #   - subtitle: Special Offers
      #     title: Get up to 30% off
      #     url: /t/special-offers/30-off
      #     image: 'meganav/promo_banner_right-second-category.jpg'
    - title: 婴儿保健
      subtitle: Categories
      url: /t/baby_supplements
      # items:
      #   - :title: Tops
      #     :url: /t/sportswear/tops
      #   - :title: Sweatshirts
      #     :url: /t/sportswear/sweatshirts
      #   - :title: Pants
      #     :url: /t/sportswear/pants
      # promo_banners:
      #   - subtitle: New collection
      #     title: Summer 2019
      #     url: /t/new-collection/summer-2019
      #     image: 'meganav/promo_banner_left-third-category.jpg'
      #   - subtitle: Special Offers
      #     title: Get up to 30% off
      #     url: /t/special-offers/30-off
      #     image: 'meganav/promo_banner_right-third-category.jpg'
